//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labixa.App_Data
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Labixa.App_Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HELPFULCONNECTION
        {
            get
            {
                return ResourceManager.GetString("HELPFULCONNECTION", resourceCulture);
            }
        }
        public static string BREAKNEWS
        {
            get
            {
                return ResourceManager.GetString("BREAKNEWS", resourceCulture);
            }
        }
        public static string Payment
        {
            get
            {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        public static string VIEWMORE
        {
            get
            {
                return ResourceManager.GetString("VIEWMORE", resourceCulture);
            }
        }
        public static string ADDCART
        {
            get
            {
                return ResourceManager.GetString("ADDCART", resourceCulture);
            }
        }
        public static string ADDRESSDETAIL
        {
            get
            {
                return ResourceManager.GetString("ADDRESSDETAIL", resourceCulture);
            }
        }
        public static string PHONEDETAIL
        {
            get
            {
                return ResourceManager.GetString("PHONEDETAIL", resourceCulture);
            }
        }
        public static string WORKINGTIMEDETAIL
        {
            get
            {
                return ResourceManager.GetString("WORKINGTIMEDETAIL", resourceCulture);
            }
        }
        public static string CoreValue
        {
            get
            {
                return ResourceManager.GetString("CoreValue", resourceCulture);
            }
        }
        public static string CONTACT
        {
            get
            {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        public static string ADDRESS
        {
            get
            {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        public static string WorkTime
        {
            get
            {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
        public static string SEND
        {
            get
            {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        public static string CONTENT
        {
            get
            {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        public static string EMAIL
        {
            get
            {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        public static string FULLNAME
        {
            get
            {
                return ResourceManager.GetString("FULLNAME", resourceCulture);
            }
        }
        public static string SENDMESSAGE
        {
            get
            {
                return ResourceManager.GetString("SENDMESSAGE", resourceCulture);
            }
        }
        public static string PHONENUMBER
        {
            get
            {
                return ResourceManager.GetString("PHONENUMBER", resourceCulture);
            }
        }
        ///
        public static string CONTACTSUS
        {
            get
            {
                return ResourceManager.GetString("CONTACTSUS", resourceCulture);
            }
        }
        public static string CONTACTS
        {
            get
            {
                return ResourceManager.GetString("CONTACTS", resourceCulture);
            }
        }
        //RECRUITMENT
        public static string RECRUITMENT
        {
            get
            {
                return ResourceManager.GetString("RECRUITMENT", resourceCulture);
            }
        }
        public static string NEWS
        {
            get
            {
                return ResourceManager.GetString("NEWS", resourceCulture);
            }
        }
        //PRODUCTS
        public static string PRODUCTS
        {
            get
            {
                return ResourceManager.GetString("PRODUCTS", resourceCulture);
            }
        }
        //
        public static string ABOUTUS
        {
            get
            {
                return ResourceManager.GetString("ABOUTUS", resourceCulture);
            }
        }
        //HOME
        public static string HOME
        {
            get
            {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        //PHONE
        public static string PHONE
        {
            get
            {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        //COMPANYADRESS
        public static string COMPANYADRESS
        {
            get
            {
                return ResourceManager.GetString("COMPANYADRESS", resourceCulture);
            }
        }
        //
        public static string FOOTER_DES
        {
            get
            {
                return ResourceManager.GetString("FOOTER_DES", resourceCulture);
            }
        }
        //BUYNOW
        public static string BUYNOW
        {
            get
            {
                return ResourceManager.GetString("BUYNOW", resourceCulture);
            }
        }
        //REFRESH_LIFE
        public static string REFRESH_LIFE
        {
            get
            {
                return ResourceManager.GetString("REFRESH_LIFE", resourceCulture);
            }
        }
        //HEALTH_RECOVERY
        public static string HEALTH_RECOVERY
        {
            get
            {
                return ResourceManager.GetString("HEALTH_RECOVERY", resourceCulture);
            }
        }
        //REVIVIFY_DES
        public static string REVIVIFY_DES
        {
            get
            {
                return ResourceManager.GetString("REVIVIFY_DES", resourceCulture);
            }
        }
        //Introduce
        public static string Introduce
        {
            get
            {
                return ResourceManager.GetString("Introduce", resourceCulture);
            }
        }
        //Far_Heart
        public static string Far_Heart
        {
            get
            {
                return ResourceManager.GetString("Far_Heart", resourceCulture);
            }
        }
        //Vision
        public static string Vision
        {
            get
            {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        public static string VisionDes
        {
            get
            {
                return ResourceManager.GetString("VisionDes", resourceCulture);
            }
        }

        //Mission
        public static string Mission
        {
            get
            {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        public static string MissionDes
        {
            get
            {
                return ResourceManager.GetString("MissionDes", resourceCulture);
            }
        }
        //ProductGroups
        public static string ProductGroups
        {
            get
            {
                return ResourceManager.GetString("ProductGroups", resourceCulture);
            }
        }
        //Best_Selling
        public static string Best_Selling
        {
            get
            {
                return ResourceManager.GetString("Best_Selling", resourceCulture);
            }
        }
        //FeaturedNews
        public static string FeaturedNews
        {
            get
            {
                return ResourceManager.GetString("FeaturedNews", resourceCulture);
            }
        }
        //ProductsDetails
        public static string ProductsDetails
        {
            get
            {
                return ResourceManager.GetString("ProductsDetails", resourceCulture);
            }
        }
        //PromotionProducts
        public static string PromotionProducts
        {
            get
            {
                return ResourceManager.GetString("PromotionProducts", resourceCulture);
            }
        }
        //NewsDetails
        public static string NewsDetails
        {
            get
            {
                return ResourceManager.GetString("NewsDetails", resourceCulture);
            }
        }
        //Featured_news
        public static string Featured_news
        {
            get
            {
                return ResourceManager.GetString("Featured_news", resourceCulture);
            }
        }
        //ReadMore
        public static string ReadMore
        {
            get
            {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        //WordTime_1
        public static string WordTime_1
        {
            get
            {
                return ResourceManager.GetString("WordTime_1", resourceCulture);
            }
        }
        public static string WordTime_2
        {
            get
            {
                return ResourceManager.GetString("WordTime_2", resourceCulture);
            }
        }
        public static string Test
        {
            get
            {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
